#Generated by Fabric Compiler ( version 2022.2-SP6.1 <build 138931> ) at Sun Jun 14 23:25:44 2026

set_arch -family Logos -device PGL12G -speedgrade -6 -package LPG144
compile -top_module body
set_arch -family Logos -device PGL12G -speedgrade -6 -package LPG144
compile -top_module body
set_arch -family Logos -device PGL12G -speedgrade -6 -package LPG144
compile -top_module body
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL12G -speedgrade -6 -package LPG144
compile -top_module body
synthesize -ads -selected_syn_tool_opt 2 
